### ISSUE TITLE
Legal Documents and consent text for website

### ISSUE THREAD

**Issue by hmert** [acikkaynak/deprem-io-frontend#1]
[CEREZ_POLITIKASI (1).docx](https://github.com/acikkaynak/deprem-io-frontend/files/10685389/CEREZ_POLITIKASI.1.docx)
[Aydnlatma_ve_Rza_Metni.docx](https://github.com/acikkaynak/deprem-io-frontend/files/10685390/Aydnlatma_ve_Rza_Metni.docx)
[GizlilikPolitikasi (1).docx](https://github.com/acikkaynak/deprem-io-frontend/files/10685391/GizlilikPolitikasi.1.docx)

```
Aydınlatma Metni'ni okudum ve kabul ediyorum
Enkaz, yıkım, yardım ve destek ihtiyaçları konusunda verdiğim bilgilerin doğru ve teyit edilmiş olduğunu, bilgi kirliliği ve yanlış uygulamalara yol açmamak için gerekli tüm önlem ve tedbirleri aldığımı, vermiş olduğum bilgilerde meydana gelen değişiklik ve güncellemeleri bildireceğimi kabul ve beyan ederim.
```

**Comment by hmert** [comment]
please add these as texts not pdfs

**Comment by karasakalmt** [comment]
https://github.com/acikkaynak/deprem-io-frontend/pull/5
