### ISSUE TITLE
Bug: Gida ve isinma Yardımı Detay 

### ISSUE THREAD

**Issue by izzetemredemir** [acikkaynak/deprem-io-frontend#100]
* Gida yardimda telefon numarası kısmında sıkıntı var  enkaz formu gibi olsun
*  Aracım var kısmındaki data gösterilmiyor

**Comment by izzetemredemir** [comment]
aynı sorun ısınma sayfasında da var

**Comment by berkanyilm** [comment]
Ben aldım bunu.

**Comment by berkanyilm** [comment]
Detay sayfalarında mı bilgi alabilir miyin ?

**Comment by izzetemredemir** [comment]
Hem form hem detayda sıkıntı var

**Comment by fatihozdil** [comment]
Aracım var kısmındaki data gösterilmiyor bu madde asagidaki issue ile birlikte cozuldu
https://github.com/acikkaynak/deprem-io-frontend/issues/93
