### ISSUE TITLE
Bug: Telefon alanı zorunlu olmayacak

### ISSUE THREAD

**Issue by izzetemredemir** [acikkaynak/deprem-io-frontend#101]
telefon alanı zorunlu olmayacak ama enkaz gida ve ısınma formlarında frontendde zorunlu onu düzeltelim

**Comment by recepdmr** [comment]
Bu issue a basliyorum.

**Comment by recepdmr** [comment]
Bu issue yapilmis gorunuyor main branch te.

**Comment by izzetemredemir** [comment]
<img width="631" alt="Ekran Resmi 2023-02-10 20 25 34" src="https://user-images.githubusercontent.com/11755605/218156684-0b326f96-4ad5-4908-8a84-1ff6a7024562.png">
Sorun devam ediyor

**Comment by yusufdeepwork** [comment]
pr'ı merge etmedik henüz o yüzden @izzetemredemir

**Comment by yusufdeepwork** [comment]
şu an pr'ı review ediyorum test ediyorum @izzetemredemir
