### ISSUE TITLE
(Mobil)Isınmaya İhtiyacım Var' a tıkladığımızda Isınma İhtiyaç Formu' da

### ISSUE THREAD

**Issue by MhmdSait** [acikkaynak/deprem-io-frontend#112]

**Comment by MhmdSait** [comment]
Isınmaya İhtiyacım Var' a tıkladığımızda Isınma İhtiyaç Formu' nda "Telefon" kısmı 10 haneye düşürülmeli, sınırlandırılmalı. 
"Kişi Sayısı:"

**Comment by karasakalmt** [comment]
Telefon kismi dusurlmesin 0 ile baslayarak yazan insanlar olabilir gerekli kontroller backend de saglaniyor kisi sayisi kontrol edilmeli  daha spesifik bir issue icin kapatiyorum

**Comment by MhmdSait** [comment]
Kusura bakmayın saat geç olunca bi dalgınlık oldu. Normalde ilk önce Google
sheete atıp oradan githuba koyuyorduk. Yanlış oldu.

11 Şub 2023 Cmt 00:42 tarihinde Mete Karasakal ***@***.***>
şunu yazdı:
