### ISSUE TITLE
yardim sagla formlari fixlenecek

### ISSUE THREAD

**Issue by karasakalmt** [acikkaynak/deprem-io-frontend#113]

**Comment by yusufdeepwork** [comment]
selam burda formlardaki sorun ne

**Comment by karasakalmt** [comment]
duplicate form var ve zaten syntax error geliyor

**Comment by yusufdeepwork** [comment]
@karasakalmt rica etsem şu an main kodunun güncel haliyle yeniden kontrol edebilir misin, syntax error göremedim ya da vs code farkedemedi. bir de hangisi duplicate form

**Comment by karasakalmt** [comment]
fixlenmis gozukuyor problem yok

**Comment by yusufdeepwork** [comment]
@karasakalmt tamamdır teşekkür ederim, sanırım kvkk branchında düzeltmiş olabiliriz baya üstünden geçip ince test ettik @fatihozdil ile
