### ISSUE TITLE
site şu anda https://bubble.io/ 'e yönlendiriyor

### ISSUE THREAD

**Issue by OnurSevket** [acikkaynak/deprem-io-frontend#116]
![image](https://user-images.githubusercontent.com/23638184/218210311-bd165daa-5fd3-46a3-b2ca-4cd2be3ee053.png)

Google Chrome
browser info : 109.0.5414.120 (Resmi Derleme) (64 bit) Sürümü

**Comment by fatihozdil** [comment]
bu mesaj bana dun de geliyordu
hangi browser kullaniyorsunuz

**Comment by OnurSevket** [comment]
Google Chrome Desktop
browser info : 109.0.5414.120 (Resmi Derleme) (64 bit) Sürümü

**Comment by fatihozdil** [comment]
çok hızlı bir şekilde live a çıkmalıyız sanırım çok geç kaldık

**Comment by karasakalmt** [comment]
canlida olan ile alakali discorddan ulasin

**Comment by OnurSevket** [comment]
Chrome güncellememe rağmen problem devam ediyor

Google Chrome Desktop
110.0.5481.78 (Resmi Derleme) (64 bit) Sürümü
