### ISSUE TITLE
deprem.io haritasının kaldırılması

### ISSUE THREAD

**Issue by yusufdeepwork** [acikkaynak/deprem-io-frontend#126]
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/57027351/218255334-d8c06804-f352-457f-ab8d-7724bbbe4e36.png">
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/57027351/218255344-3d2f3d3e-8685-4321-a33d-3c2612d0f051.png">

**Comment by karasakalmt** [comment]
https://github.com/acikkaynak/deprem-io-frontend/pull/127
