### ISSUE TITLE
Isınma İhtiyacı Olanlar Listeleme Yapmıyor

### ISSUE THREAD

**Issue by Narghos** [acikkaynak/deprem-io-frontend#134]
Bug Definition:

 Isınma ihtiyacı olanlar butonuna tıklandığında ihtiyaçlar görünmüyor. Filtreleme üzerinde bulunan sayfa değiştirmeye tıklandığında sayfa 2/2 oluyor ve ihtiyaç listesi sergileniyor.

Bug environment 

https://dev.thechainlist.io/

Describe how you are producing the bug step by step

1. Go to 'https://dev.thechainlist.io/'
2. Click 'Isınma İhtiyacı Olanlar'
3.  Herhangi bir data olmadığını gör.
4. <1/undefined> butonundan sağa  ">" tıkla
5. Sayfa 2/2 olduğunu ve ihgtiyaçların listelendiğini gör.

Expected Behaviour

Isınma İhtiyacı Olanlar butonuna tıklandığında güncel datanın sergilenmesi.

 Screen shots

https://www.loom.com/share/f507b8528f5b49139a2c03192fdca5b7

Desktop Information

Windows 11 Chrome 109.0.5414.120

**Comment by karasakalmt** [comment]
@mthocur @onuruci ikinize de verdim biriniz yapsin lutfen

**Comment by mthocur** [comment]
backend sorunu var, @izzetemredemir bakıyor.

**Comment by mthocur** [comment]
@izzetemredemir backend'de fixledi, sorun çözüldü
