### ISSUE TITLE
Iletişim Formundaki Notification tooltipi ingilizce görünüyor

### ISSUE THREAD

**Issue by ilyastunch** [acikkaynak/deprem-io-frontend#140]
## Bug Definition
Iletişim Formundaki Notificationlar Ing görünüyor
Hata tüm inputlar için geçerli

-- Please add discord contact information
 discord username: @eliasT#5718 

## Bug environment
deprem io dev env.
https://dev.thechainlist.io/iletisim.html

## Describe how you are producing the bug step by step

1. Go to deprem io home page 
2. Click Iletisim button 
3. Avoid filling isim&soyisim
4. Click Gonder button

## Expected Behaviour
No

## Screen shots
![image](https://user-images.githubusercontent.com/62998233/218261091-c96b61c8-1fe4-40c6-83b6-224be898a8bd.png)

## Desktop Information
- Operating System: Windows 10
- BrowserChrome latest
- Version 110.0.5481.78

**Comment by yusufdeepwork** [comment]
@ilyastunch selam, browser language söyler misin? bende böyle çünkü
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/57027351/218268817-0dfb4d1e-874d-4445-b59e-eb8ead2c4292.png">

**Comment by yusufdeepwork** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/57027351/218268892-df4aad41-d869-43fd-bea6-7fd83ca1969e.png">
@fatihfurkanaydemir sen de bakabilir misin @karasakalmt sen de

**Comment by karasakalmt** [comment]
su an onemsiz

**Comment by fatihfurkanaydemir** [comment]
Browser diline göre verilen uyarı dili değiştiği için düzeltmeye gerek kalmadı o yüzden issue kapatıldı.

**Comment by ilyastunch** [comment]
browser dili ingilizceydi evet
