### ISSUE TITLE
Yardım Al Forma isim tek parça halinde girilirse sansür olmuyor.

### ISSUE THREAD

**Issue by Narghos** [acikkaynak/deprem-io-frontend#142]
Yardım al formlarına isim tek parça olarak girilirse isim sansürlenmiyor.

![image](https://user-images.githubusercontent.com/98612698/218261657-1073e442-f8e8-4e9f-9546-e20f6af78ca8.png)

**Comment by karasakalmt** [comment]
technic debt fixlenecek acil degil @izzetemredemir
