### ISSUE TITLE
Yardım İstekleri Sayfasında Açıklaması Uzun istekler Sayfayı Bozuyor

### ISSUE THREAD

**Issue by ilyastunch** [acikkaynak/deprem-io-frontend#145]
## Bug Definition
Yardım İstekleri Sayfasında Açıklaması Uzun istekler Sayfayı Bozuyor
Belli Karakter Üzerini sonuna üç nokta eklenerek kısaltılıp sayfanın yapısı korunabilir

-- Please add discord contact information
 discord username: @eliasT#5718 

## Bug environment
deprem io dev env.
https://dev.thechainlist.io/yardim-istekleri/enkaz.html?yardimDurumu=enkaz&isim=test

## Describe how you are producing the bug step by step

1. Deprem.io ana sayfasına git
2. Yardım Listeleri altında enkaz altında olanlar butonuna tıkla
3. Isım soyisim alanına bir değer gir
4. Filtrele butonuna tıkla

## Expected Behaviour
Uzun açıklamalı itemlerin sayfa yapısını bozmaması beklenir

## Screen shots/recordings
https://user-images.githubusercontent.com/62998233/218263012-be4fad29-59ec-4f32-956b-e6dbd9930030.mp4

## Desktop Information
- Operating System: Windows 10
- BrowserChrome latest
- Version 110.0.5481.78

**Comment by onuruci** [comment]
Fixed
