### ISSUE TITLE
deprem io daki light tema ile birebir aynısı yapılacak, style conflictler çözülecek

### ISSUE THREAD

**Issue by yusufdeepwork** [acikkaynak/deprem-io-frontend#146]

**Comment by onuruci** [comment]
Burda itemler ve filtering kısmını yaptım fakat ufak detaylar elbet var mesela render edilen svg ler gibi arka planı kapatıyorlar.

**Comment by yusufdeepwork** [comment]
@onuruci pr açtın mı abi bakayım

**Comment by onuruci** [comment]
mergeledim şuan pull yaparsan localinde gözükür

**Comment by karasakalmt** [comment]
<img width="1000" alt="Screen Shot 2023-02-12 at 03 46 13" src="https://user-images.githubusercontent.com/32202283/218303201-08eea530-31cf-452e-9493-f0c3122f8ae1.png">
burda arkaplan beyaz olsun  
 


<img width="1000" alt="Screen Shot 2023-02-12 at 03 46 29" src="https://user-images.githubusercontent.com/32202283/218303211-5213c571-df25-4142-8ae1-56d8ab89fa27.png">
<img width="471" alt="Screen Shot 2023-02-12 at 03 46 44" src="https://user-images.githubusercontent.com/32202283/218303216-3a12edf6-18a0-40dc-81ce-c4f80dd064db.png">
yazilar mavi uzerine beyaz olsun

**Comment by yusufdeepwork** [comment]
tamamdır
