### ISSUE TITLE
Yardım İstekleri sayfasında itemlerda üstteki itemlarda görsel bozulma 

### ISSUE THREAD

**Issue by ilyastunch** [acikkaynak/deprem-io-frontend#149]
## Bug Definition
Yardım İstekleri sayfasında itemlerda üstteki itemlarda görsel bozulma 

-- Please add discord contact information
 discord username: @eliasT#5718 

## Bug environment
deprem io dev env.
https://dev.thechainlist.io/yardim-istekleri/enkaz.html

## Describe how you are producing the bug step by step

1. Deprem.io ana sayfasına git
2. Yardım Listeleri altında enkaz altında olanlar butonuna tıkla

## Expected Behaviour
Listelenen itemların doğru görünmesi beklenir

## Screen shots
![image](https://user-images.githubusercontent.com/62998233/218263712-03dc32b2-f33e-4b53-b391-af4bae7e6e45.png)

## Desktop Information
- Operating System: Windows 10
- BrowserChrome latest
- Version 110.0.5481.78

**Comment by fatihfurkanaydemir** [comment]
Yeni eklenen hiçbir datada bu sorun gözükmüyor şimdilik kapatabilirsiniz isterseniz.

**Comment by karasakalmt** [comment]
@izzetemredemir sanirim xss ile ilgili oyleyse kapatalim

**Comment by izzetemredemir** [comment]
Bu sorun çözüldü
