### ISSUE TITLE
Gıda / Isınma / Enkaz liste saygalarına yeni item oluşturma butonu eklenmesi

### ISSUE THREAD

**Issue by ilyastunch** [acikkaynak/deprem-io-frontend#154]
Listelerin bulunduğu sayfalara Yeni Talep Oluştur Şeklinde bir button eklenerek kayıt oluşturma sayfalarına yönlendirebilir.

**Comment by karasakalmt** [comment]
duplikasyon konusunda problem yaratmaya tesvik edebilir
