### ISSUE TITLE
Tüm Kayıt Formlarında aynı isimden ikinci bir kayıt oluşturmaya izin vermiyor

### ISSUE THREAD

**Issue by ilyastunch** [acikkaynak/deprem-io-frontend#156]
## Bug Definition
Tüm Kayıt Formlarında aynı isimden ikinci bir kayıt oluşturmaya izin vermiyor
Steplerde ve recordingde tek form üzerinde gösteriliyor ancak bütün formlarda aynı issue var
Ör: Ahmet isminde bir kullanıcı bir kayıt açtığında başka bir ahmet isminde kullanıcı kayıt oluşturamıyor.
Burada input sadece isim de kabul ettiği gibi isim soy isim de kabul ediyor

-- Please add discord contact information
 discord username: @eliasT#5718 

## Bug environment
deprem io dev env.
https://dev.thechainlist.io/yardim-istekleri/enkaz.html?yardimDurumu=enkaz&isim=test

## Describe how you are producing the bug step by step

1. Deprem.io ana sayfasına git
2. Yardım Al modülü altında gıdaya ihtiyacım var butonuna tıkla
3. Isım olarak specific bir isim gir 
4. Zorunlu alanları doldur ve kaydet
5. Aynı isimde yeni kayıt oluştur ve kaydet
6. Hata popı aldığını onayla

## Expected Behaviour
Aynı isimde olan kullanıcılar kayıt oluşturabilmeli

## Screen shots/recordings

https://user-images.githubusercontent.com/62998233/218266775-8b877086-cfd3-403f-83f9-fd5e082f1b03.mp4

## Desktop Information
- Operating System: Windows 10
- BrowserChrome latest
- Version 110.0.5481.78

**Comment by izzetemredemir** [comment]
Adres ve isim aynı ise izin vermez
