### ISSUE TITLE
İletişim Formu - Mail Kısmı Nokta İşaretinin Zorunlu Olmaması

### ISSUE THREAD

**Issue by berfinhazalkaya** [acikkaynak/deprem-io-frontend#161]
**Describe the bug**
İletişim formunda mail kısmında .com / .net yazarken nokta koymadığımızda yine de iletişim formunu başarılı bir şekilde gönderebiliyoruz.  Örneğin test@gmailcom adresini kullanarak başarılı bir şekilde iletişim formunu gönderebiliyoruz. Mail kısmında @ işareti zorunlu fakat nokta konulması zorunlu değil

**Page Link**
İletişim Sayfası : https://dev.thechainlist.io/iletisim.html

**To Reproduce**
1. deprem.io sayfasına git
2. Ana sayfadaki iletişim butonuna tıkla
3. Açılan sayfadaki alanları doldur
4. Mail kısmını doldururken "nokta" **kullanma**
5. KVKK'yı onayla
6. Gönder butonuna tıkla

**Expected behavior**
Email adresinde com/net/tr den önce nokta yazılmalıdır. Nokta yazılmadığında mail adresi bulunamayacaktır ve mail giitmeyecektir. Nokta zorunlu tutulmalıdır.

**Screenshots**
![image](https://user-images.githubusercontent.com/70517386/218272349-b6ec1a9a-a0ae-45bd-9c14-5e1c8f6ce11d.png)

**Desktop (please complete the following information):**
- Windows 10 Sürüm 21H2
- Chrome 109.0.5414.121(64 bit)

**Comment by asaidozdemir** [comment]
Bu başlıkla ilgili Pull Request attım.
https://github.com/acikkaynak/deprem-io-frontend/pull/165

**Comment by asaidozdemir** [comment]
#165
