### ISSUE TITLE
Enkaz, Gıda ve Isınma detay sayfasında yer alan Google Maps'te Aç butonu aynı sayfaya gidiyor. 

### ISSUE THREAD

**Issue by cagatayturkann** [acikkaynak/deprem-io-frontend#166]
**Describe the bug**
Enkaz, Gıda ve Isınma detay sayfasında yer alan Google Maps'te Aç butonu yeni sekmede bulunulan aynı sayfayı açıyor. 

**To Reproduce**
1. Enkaz, Gıda veya Isınma herhangi bir sayfaya gidilir. 
2. Herhangi bir talebe ait Detaya Git linkine tıklanır. 
3. Detay sayfasında bulunan Google Maps'te Aç butonuna tıklanır. 
4. Bulunulan sayfa tekrar yeni sekmede açılır. 

**Expected behavior**
İnput alanında bulunan adres tarifine göre linke gitmeli ? 

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Brave
 - Version: 1.48

**Comment by fatihfurkanaydemir** [comment]
#176 ile fixlendi.
