### ISSUE TITLE
Enkaz Yardım Detay Sayfası - Yardım Kaydı Oluşturma

### ISSUE THREAD

**Issue by berfinhazalkaya** [acikkaynak/deprem-io-frontend#170]
**Describe the bug**
Enkaz yardımı detay sayfasında, yardım kaydı oluşturmak istediğimizde alanları doldurup kaydet butonuna bastığımızda "PostID Bulunamadı" hatası alıyoruz. Hatanın ekran görüntüsü aşağıya eklenmiştir.

**To Reproduce**
1. deprem.io sayfasını aç
2. "Ben / Tanıdığım Enkazda" butonuna tıkla
3.  "Mevcut Kayıtlara Git" butonuna tıkla
4.  Herhangi bir kayıt için "Detaya Git" butonuna tıkla
5. Enkaz detay sayfasında yardım talebi oluştur kısmındaki bilgileri doldur
6. KVKK onayla
7. Kaydet Butonuna Tıkla

**Expected behavior**
Yardım talep formunun başarıyla gönderilmesi gerekmektedir.

**Screenshots**
![image](https://user-images.githubusercontent.com/70517386/218275136-df68c427-8f33-4bec-902f-496479be9dc2.png)

**Desktop (please complete the following information):**
- Windows 10 Sürüm 21H2
- Chrome 109.0.5414.121(64bit)

**Comment by berkanyilm** [comment]
Backend tarafını kontrol ediyorum.

**Comment by berkanyilm** [comment]
Genel revize yapıldı, test edilmesi için @cagatayturkan'a verildi.

**Comment by berkanyilm** [comment]
@cagatayturkann takip edildi. Detay sayfasındaki url değiştirilince problem giderildi. @izzetemredemir ile belirtilen sayfadaki url değiştirildi.
