### ISSUE TITLE
Gıda Sağlama Detay sayfalarında bulunan yeni kayıt ekleme formu internal server error hatası veriyor. 

### ISSUE THREAD

**Issue by cagatayturkann** [acikkaynak/deprem-io-frontend#174]
**Describe the bug**
Gıda Sağlama Detay sayfalarında bulunan yeni kayıt ekleme formu internal server error hatası veriyor. 

**To Reproduce**
1. Gıda Sağlama detay sayfasına gidilir. 
2. Yeni kayıt formu doldurulur
3. Gönder butona tıklanır
4. Hata alınır. 

**Expected behavior**
Formun başarılı şekilde gönderilebilmesi. 

**Screenshots**
https://i.ibb.co/ZSZhSZz/2023-02-11-21-49-37.jpg
https://i.ibb.co/6NxYS56/Screen-Shot-2023-02-11-at-21-50-48.png

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Brave
 - Version: 1.48

**Comment by Tantoony** [comment]
bakıyorum şimdi

**Comment by cagatayturkann** [comment]
@berkanyilm ile takip ediliyor. Emre ile konuşuldu front tarafında end point değişikliği sonrası tekrar test edilecek.
