### ISSUE TITLE
Yardım Listelerinde Filtreleme Sonrası Page Sayfasının Undefined Olarak Gözükmesi

### ISSUE THREAD

**Issue by MustafaKANLI** [acikkaynak/deprem-io-frontend#175]
**Describe the bug**
Enkaz altında olanlar, gıda ihtiyacı olanlar gibi sayfalarda filtreleme yaptıktan sonra pagination'da toplam sayfa undefined geliyor

**To Reproduce**
1. Ana Sayfaya git
2. Yardım Listeleri altında enkaz altında olanlar butonuna tıkla
3. Isım soyisim alanına bir değer gir
4. Filtrele butonuna tıkla

**Expected behavior**
Filtreleme sonucu gözüken sayfa sayısının doğru gözükmesi beklenir

**Screenshots**
![image](https://user-images.githubusercontent.com/58121211/218276854-e79952ce-8d78-4ea0-8ca5-b16e3c8dcb72.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by fatihfurkanaydemir** [comment]
#148 ile duplicate
