### ISSUE TITLE
Yardım Al Seçenekleri - Aynı Kişinin Birden Fazla Yardım Alamaması

### ISSUE THREAD

**Issue by berfinhazalkaya** [acikkaynak/deprem-io-frontend#177]
**Describe the bug**
Yardım Al seçeneklerinden (Ben/Tanıdığım Enkazda, Gıdaya İhtiyacım Var ,Isınmaya İhtiyacım Var) herhangi bir yardım seçeneğini doldurduktan sonra aynı bilgilerle başka yardım seçeneğini dolduramıyoruz. Aynı kişinin hem gıdaya hem de ısınmaya ihtiyacı olabileceğinden aynı bilgilerle farklı yardım seçenekleri doldurulmalı fakat aynı bilgiler ile aynı yardım seçeneği doldurulmamalıdır.

**To Reproduce**
1. deprem.io sayfasını aç
2. "Yardım Al" seçeneklerinden herhangi birini doldur
3.  Aynı bilgilerle başka bir yardım formunu doldur

**Expected behavior**
Aynı kullanıcı bilgileri ile farklı yardım al formları doldurulabilmeli, aynı yardım al formları doldurulamamalıdır.

**Desktop (please complete the following information):**
- Windows 10 Sürüm 21H2
- Chrome 109.0.5414.121(64 bit)

**Comment by karasakalmt** [comment]
https://github.com/acikkaynak/deprem-io-frontend/issues/156 duplicate
