### ISSUE TITLE
form submissiondan sonra ilgili listeye redirect edilmeli

### ISSUE THREAD

**Issue by karasakalmt** [acikkaynak/deprem-io-frontend#18]
ornegin gida formu submit edildiyse onay mesaji gozuktukten sonra gida bekleyenlerin listesine gecilebilir

**Comment by BarkinBayzin** [comment]
ben yardımcı olabilirim dilerseniz, swal mı kullanıyorsunuz ?

**Comment by karasakalmt** [comment]
uygundur https://t.me/+InSwFkHY5HBhNTFk burdan iletisime gecebilirsiniz
