### ISSUE TITLE
Köylerin yardım durumu geri butonu çalışmıyor

### ISSUE THREAD

**Issue by emnkvk** [acikkaynak/deprem-io-frontend#187]
**Köylerin yardım durumu geri butonu çalışmıyor**
Köylerin Yardım Durumu sayfasında Geri tuşuna basıldığı zaman deprem.io sayfasına geri dönülmüyor.

**https://deprem.io/*
1. Yardım Listeleri'
2. Köylerin Yardım Durumuna Tıkla
3. Geri butonuna bas

**Expected behavior**
Butona basıldığında deprem.io sayfasına dönmeli

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser : Chrome, Firefox

**Smartphone :Xiaomi **
 - Device: [MI 8 Lite]
 - OS: Android 8.1.0]
 - Browser [Chromei]

**Smartphone :Iphone **
 - Device: [XS Max]
 - OS: [IOS 16.2]
 - Browser [Chromei]

**Comment by karasakalmt** [comment]
canlida ki versiyon oldugu icin alakasiz
