### ISSUE TITLE
telefonlarin basina eklenen +90lar silinsin

### ISSUE THREAD

**Issue by karasakalmt** [acikkaynak/deprem-io-frontend#194]
backend e giden formatlarda bozukluk yaratiyor

**Comment by onuruci** [comment]
Telefon ile ilgili parser yapmıştım lütfen silmeyin. tekrardan ekliyorum

**Comment by onuruci** [comment]
Backendde düzeltilmiş hata. Ben +90 , 90 ve 0 ları parse ederek yollamayı ekliyorum

**Comment by karasakalmt** [comment]
Kapatalim issueyu kafa karisikligi yaratmasin diger formlari da ekleyelim
