### ISSUE TITLE
Yardım Al kısmındaki butonda ve sayfada yazım hatası

### ISSUE THREAD

**Issue by syndrakes** [acikkaynak/deprem-io-frontend#2]
<img width="253" alt="hata1" src="https://user-images.githubusercontent.com/76838467/217594520-b38c0a1f-92c6-4b89-9df3-90059384a913.png">
<img width="362" alt="hata 2" src="https://user-images.githubusercontent.com/76838467/217594608-f6287832-0bd4-4b11-a57b-7a9c20a7aa86.png">

**Comment by oucar** [comment]
Gorunuse gore duzeltilmis, issue kapatilabilir.

**Comment by karasakalmt** [comment]
iç sayfada Depremzede Bildirim Formu şeklinde yazdık ana sayfada kısa şekilde yazılı daha rahat gözükmesi açısından
