### ISSUE TITLE
Ayrinti sayfalarinda ki yanlis alanlar

### ISSUE THREAD

**Issue by karasakalmt** [acikkaynak/deprem-io-frontend#201]
ornegin gida tasima da gidilen sehir ve hedef sehir detay sayfasinda gozukmuyor bu tarz sorunlar butun sayfalar icin fixlenmeli

**Comment by onuruci** [comment]
Araç Durumunu gereken yerlere ekledim

**Comment by onuruci** [comment]
Detay formlarında yardım ve yardım et objelerinde son durum ile ilgili farklı seçenekler olması gerek. Uygun şekilde düzelttim.

**Comment by onuruci** [comment]
Fizik Durumu ve Ayrıntı alanları düzelttim.

**Comment by onuruci** [comment]
Başka eksik bulamadım issue yu kapatıyorum
