### ISSUE TITLE
Fiziki durum hakkında bilgi detay sayfasında gelmiyor

### ISSUE THREAD

**Issue by Corepany** [acikkaynak/deprem-io-frontend#202]
**Describe the bug**
Fiziki durum hakkında bilgi detay sayfasında gelmiyor

**To Reproduce**
1. Isınmaya ihtiyacım var formunu doldurdum
2. Tüm alanları doldurdum
3. Formu başarı ile gönderdim

**Expected behavior**
Doldurduğumuz form bilgileri görüntülenmeli. Fiziki durum bilgisi de gelmeli

**Screenshots**
<img width="700" alt="image" src="https://user-images.githubusercontent.com/9643129/218311296-ac1839ea-34df-43dd-84bd-67a651fe1171.png">

<img width="1059" alt="image" src="https://user-images.githubusercontent.com/9643129/218311307-4ec6e446-d33d-462a-842b-561aa9fab1a6.png">

**Comment by onuruci** [comment]
Düzelttim
