### ISSUE TITLE
ikinci telefon eklerken formatı doğru girsem bile valide olmuyor

### ISSUE THREAD

**Issue by Corepany** [acikkaynak/deprem-io-frontend#203]
**Describe the bug**
ikinci telefon eklerken formatı doğru girsem bile valide olmuyor
Telefon validation hatasının mesajında ki format yanlış. Başında sıfır olmaması gerekiyor

**To Reproduce**
1. Isınma ihtiyacım var formuna geldim
2. Formu doldurup ikinci telefon ekledim
3. Telefon formatı doğru olsa da form gönderilemedi

**Expected behavior**
Form gönderilebilmeli. Telefon hata mesajı düzeltilmeli. istenilen format doğru olarak mesaja yazılmalı

**Screenshots**
<img width="779" alt="image" src="https://user-images.githubusercontent.com/9643129/218311486-13d5c1a1-c096-4611-8873-114e5a8763d4.png">

**Comment by onuruci** [comment]
https://github.com/acikkaynak/deprem-io-frontend/issues/180

Aynı hata mı acaba. Aynıysa kapatalım bunu

**Comment by karasakalmt** [comment]
https://github.com/acikkaynak/deprem-io-frontend/issues/180 duplike
