### ISSUE TITLE
CS/DP-17: ısınma  ihtiyacı olanlar filtresi liste görünümü- listing görünümü

### ISSUE THREAD

**Issue by ibrahimF01** [acikkaynak/deprem-io-frontend#208]
**Bug Açıklama**
"ısınma  ihtiyacı olanlar filtresi liste görünümü- listing görünümü" senaryosu beklenen sonucu karşılamıyor.

**Test Adımları**
Filtrelenen adedi
Pagination
yardım durumu filtresi görünümü
Aciliyet filtresi görünümü
lokasyon görünümü
ad soyad görünümü
cep telefonu görünümü
son güncellenme tarih, saat, x süre önce görünümü,
bildirim data id görünümü
Detaya git buton görünümü

**Beklenen Durum**
Filtrelenen sol üstteki count un integer olarak doğru count sayısı döndüğünden emin olunur
Her sayfada max 10 satır olur, toplam geri dönen data sayısına göre sağ alt ve sağ üstte doğru sayıda pagination count geldiğinden emin olunur-> ör: 141 satır 
pagination sayısı 15 olmalı, sayfalar arası geçişte performans sorunu olmadığında mükerrer data olmadığından , sayfa geçişlerinde filtreye uygun data dönmeye devam ettiğinden emin olunur
yardım durumu filtresi :her satırın sol üstünde ilgili datanın yardım durumu statüsü 
colar code'a göre doğru şekilde geldiğinden emin olunur.Yardım bekleniyor: kırmızı,yardım edildi: yeşil, yetersiz bilgi:turuncu,yardım edilemedi:gri
aciliyet filtresi:yardım durumu statüsü yanında ilgili datanın doğru aciliyet bilgisi geldiğinden emin olunur: Kritik, orta, normal(color code yok)
lokasyon görünümü: datanın adres bilgisinin her satırda sol altta harita ikonun yanın doğru geldiğinden emin olunur
ad soyad bilgisinin ilk harflerinin açık sonraki harflerinin *** lı olarak geldiği gözlenir
cep telefonu bilgisinin girili kayıtlar için gözlemlendiğinden emin olunur
son güncellenme bilgisinin sırayla: tarih-saat-x dk/saat önce olarak görünür
bildirim datasının id'si görüntülenir
detaya git butonu görüntülenir ve cta'ının ilgili datanın doğru detay sayfasına yönlendirdiği görüntülenir

**Screenshots**
![image](https://user-images.githubusercontent.com/108164455/218315107-aebc8cd0-b426-44e7-96a8-c9372bc7c5a6.png)

**Desktop :**
 - Win: [Windows 10]
 - Browser [chrome]
 - Version [109.0.5414.120 (Resmi Derleme) (64 bit) Sürümü]

**Ek içerik**
Resimde görüldüğü gibi listelenen adeti görünmüyor. Kaç kişi beklemede, kaç kişiye yardım yapıldı, bunu görmek önemli. 
Dublicate bug olabilir. Çözüldüyse dikkate almayın.

**Comment by fatihfurkanaydemir** [comment]
#143, #148 ve #206 da bakılıyor.
