### ISSUE TITLE
Yatay da scroll oluşması. Sayfanın ekran dışına taşması. [Mobil]

### ISSUE THREAD

**Issue by Corepany** [acikkaynak/deprem-io-frontend#219]
**Describe the bug**
Yatay da scroll oluşması. Sayfanın ekran dışına taşması. Mobil
**To Reproduce**
1. Ana sayfaya geldim
2. Herhangi bir form sayfasını tıkladım

**Expected behavior**
Sayfanın yatayda scroll olmaması. Sayfaya tam oturması.

**Screenshots**
<img width="458" alt="image" src="https://user-images.githubusercontent.com/9643129/218336269-cb04a359-c2f4-46a5-87ee-53e24632ce43.png">

**Comment by karasakalmt** [comment]
<img width="207" alt="Screen Shot 2023-02-12 at 23 51 14" src="https://user-images.githubusercontent.com/32202283/218336342-8bd73973-0ee4-49ff-964c-08d67d750eb3.png">

bende problem gozumuyor

**Comment by Corepany** [comment]
Fixed Closed
