### ISSUE TITLE
Karanlık mod da başarılı ve hatalı dialogları boş geliyor

### ISSUE THREAD

**Issue by Corepany** [acikkaynak/deprem-io-frontend#222]
**Describe the bug**

**To Reproduce**
1. Çadır formu doldurup gönderildi

**Expected behavior**
Mesajın görünmesi

**Screenshots**
<img width="787" alt="image" src="https://user-images.githubusercontent.com/9643129/218338331-09c36aca-6814-4413-908c-0a7f2d90fa84.png">

**Comment by karasakalmt** [comment]
fixed
