### ISSUE TITLE
Paylaş butonu ile birlikte açılan container boş geliyor

### ISSUE THREAD

**Issue by devrimcavusoglu** [acikkaynak/deprem-io-frontend#27]
İleriye yönelik bir geliştirme olup olmayacağını bilmiyorum ama bu buton ile açılan container boş geliyor.

![image](https://user-images.githubusercontent.com/46989091/217757792-9b18a4d6-4428-4efb-b205-82d13fcac55d.png)

**Comment by omercan3** [comment]
Merhaba, kontrol ediyorum. Yapabilirsem kodu güncelleyip paylaşacağım. İletişim için discorddan ekleyebilirsiniz:
Ömer Baylam#9476

**Comment by omercan3** [comment]
Merhaba, bahsettiğiniz butonu kontrol ettiğimde bir sıkıntı göremedim. "Paylaş" butonu olduğunu doğrularsanız şöyle bir kanıya vardım.
Siteye patch atılmış sanırsam öncesi ve sonrası şu şekilde görünüyor. Tam patch anında siteye girdiyseniz sorunla karşılaşmış olabilirsiniz:
Öncesi: https://prnt.sc/8m25BOXu75vI
Sonrası: https://prnt.sc/ZH0V_7np3Aw6

**Comment by hsyngul** [comment]
bu kısmı dün gece ben yapmıştım sorun varsa tekrar bakabilirim @omercan3 @devrimcavusoglu

**Comment by CanCodes** [comment]
Şu an kontrol ettim, hala gözükmüyor
![image](https://user-images.githubusercontent.com/32599057/217789371-50a21177-dc27-4b2b-b03c-d3dc7d391d49.png)

**Comment by devrimcavusoglu** [comment]
Bu konuda şöyle bir bilgi vermek sanırım daha faydalı olur. 

```
platform: ubuntu-22.04 LTS (5.15.0-56-generic)
browser: Google Chrome Version 110.0.5481.77 (Official Build) (64-bit) 
browser2: Firefox 109.0.1 (64-bit)
```
Ubuntu üzerinde bu browserlar ile görüntüleyemiyorum. Not olarak VPN ile de butonlar gözüktü ama ubuntu üzerinden VPN'siz girdiğimde source'ta gördüğümü aşağıda paylaşıyorum benim localimde.
![image](https://user-images.githubusercontent.com/46989091/217795232-22deecf9-6e7c-45f4-b184-354d8906967d.png)

NOT: Mobil'den girdiğimde görüntüleyebildim.

**Comment by karasakalmt** [comment]
bu versiyonla alakali degil
