### ISSUE TITLE
Adblock olan tarayicilarda site kullanilamiyor

### ISSUE THREAD

**Issue by abozgeyik** [acikkaynak/deprem-io-frontend#28]
**Problem:**
Adblocker olan tarayicilarda site kullanilamiyor. Bubble banner blocklandigi icin asagidaki banner cikiyor ve bir sure site https://bubble.io/ adresine yonlendiriliyor.

`This app is a free plan and should have a Bubble banner. Please upgrade to remove this banner. Removing or altering the banner in any way is against Bubble terms and can lead to your account termination.`

**Ortam:** 
Chrome(macos) + uBlock

**Comment by erhanalankus** [comment]
@abozgeyik selam,
macos chrome, ublock origin aktif şekilde https://deprem.io/ sitesi bende açılıyor. tekrar dener misin?
![Screenshot 2023-02-09 at 13 33 59](https://user-images.githubusercontent.com/8477179/217788636-551ebaee-7364-4487-84c8-ef0cb60ea980.png)

**Comment by erhanalankus** [comment]
@abozgeyik issue'yu kapatabilir misin?
