### ISSUE TITLE
Kronik rahatsızlıgı olanların ilaç problemi ile alakalı kısım

### ISSUE THREAD

**Issue by buraktuzlutas** [acikkaynak/deprem-io-frontend#31]
İsteğiniz şeyi tanımlayın
Bu alanda bölgeden sürekli girip çıkan ekiplerin kronik rahatsızlığı olan insanlara ilaç tedariğinde yardımcı olması amaçlı bi kısım uygun görülmesi halinde eklenebilir.
 _Bölgede bu amaçlı arayış çok fazlaymış, kronik rahatsızlığı olanlar o tarafa yardıma gelenlerden talep ediyormuş._
buraktuzlutas#4581

Değerlendirdiğiniz alternatifleri tanımlayın
Yardım Listeleri kısmına İlaç ihtiyacı olanlar bölge yakınlarından ilaç tedariği konusunda iletişime geçebilmeli

Ek Bağlam
![ilaceczane](https://user-images.githubusercontent.com/7132788/217792566-2a521d93-67f2-4a83-8663-c00c0b658e2a.png)

**Comment by karasakalmt** [comment]
Su an bug fixlerle ugrasacagiz tekrardan bunu iletecegim mumkunse ekleyecegiz
