### ISSUE TITLE
Yardım talep formlarında birden fazla telefon numarası girilebilmesi

### ISSUE THREAD

**Issue by zafergurel** [acikkaynak/deprem-io-frontend#33]
Afet bölgelerinde cep telefonu şarjı sorunu olduğu aşikar. Birden fazla telefon numarası alanı olması gerekli diye düşünüyorum.

**Comment by izzetemredemir** [comment]
Backende eklendi  

{
    "yardimTipi": "Gıda",
    "adSoyad": "John Doe",
    "telefon": "555-555-5555",
    "yedekTelefonlar": ["555-555-5556", "555-555-5557"],
    "email": "johndoe@example.com",
    "adres": "123 Main St",
    "adresTarifi": "2nd floor, apartment 4B",
    "acilDurum": "normal",
    "kisiSayisi": "3",
    "yardimDurumu": "bekleniyor",
    "fizikiDurum": "normal",
    "googleMapLink": "https://maps.google.com/maps?q=123+Main+St",
    "tweetLink": "https://twitter.com/johndoe/status/1234567890",
     "fields-status": "test-status",
     "fields-yenialan": "ekstrabilgi"
   
}

**Comment by zafergurel** [comment]
@izzetemredemir 
Form değerleri göndermek için aşağıdaki şekilde bir yöntem kullanılmış:

```
xhr.send(JSON.stringify(Object.fromEntries(formData)));
```

Dolayısıyla, tek seviye JSON verisi oluşturuluyor. Ben de bu yüzden telefon_2 ve telefon_3 id'si vererek iki alan ekledim. Model de karşılığı olur diye düşünerek.

Gönderdiğiniz kodda ise yedekTelefonlar diye bir array alanı var. Bu modele uygun şekilde post verisi oluşturmek için yukarıdaki JS kodunu değiştirmek gerekecek ki çok da içime sinen bir değişiklik olmayacaktır.

Önerim backend modeline telefon_2 ve telefon_3 alanları eklemek (yedekTelefonlar yerine). Daha pratik olacaktır diye düşünüyorum. 

Ne dersiniz?
