### ISSUE TITLE
twitter share link'i çalışmıyor

### ISSUE THREAD

**Issue by ondokuzz** [acikkaynak/deprem-io-frontend#4]
ana sayfadaki paylaş kısmındaki twitter share çalışmıyor.

**Comment by karasakalmt** [comment]
@mthocur bakabilir misin

**Comment by hsyngul** [comment]
buraya bi ss atabilir misiniz @ondokuzz ben yardımcı olayım müsaitim @karasakalmt

**Comment by karasakalmt** [comment]
@hsyngul bu repository de henuz paylasma secenekleri yok musaitseniz paylasma seceneklerini ekleyebilirsiniz size assign edebilirim

**Comment by hsyngul** [comment]
@karasakalmt assign edebilirsiniz hocam. Yalnız bi introya ihtiyacım olacak ilgili discord kanalına alırsanız çok sevinirim

**Comment by karasakalmt** [comment]
@hsyngul karasakalmt#1437 ulasabilirsiniz

**Comment by ondokuzz** [comment]
twitter kapatıldığı için çalışmıyomuş. vpn ile girince çalıştı.
issue'yu kapatabiliriz.

**Comment by hsyngul** [comment]
@ondokuzz Huseyin Gul#0295 discord dan ekleyebilirseniz diğer issue lar için yardımcı olabiliriz

**Comment by ondokuzz** [comment]
ben de ekli değilim. ekleyen olursa beni de eklesin. murat#1927

**Comment by karasakalmt** [comment]
bu bu repoya ait degil bizim eklememiz gerekiyor @hsyngul ilgileniyor

**Comment by hsyngul** [comment]
https://github.com/acikkaynak/deprem-io-frontend/pull/11 @karasakalmt issue yu kapatabiliriz
