### ISSUE TITLE
Main nav share link alignment

### ISSUE THREAD

**Issue by mthocur** [acikkaynak/deprem-io-frontend#40]
share link is not aligned

can be fixed with css display flex on ".share-button-wrapper" element

![Ekran Resmi 2023-02-09 15 57 48](https://user-images.githubusercontent.com/23366853/217819349-4f359ea6-09c6-40ea-ac9f-faac87d23a96.png)

**Comment by berkanyilm** [comment]
Tüm header tarafı fixlensin mi ?

**Comment by mthocur** [comment]
> Tüm header tarafı fixlensin mi ?

şimdilik detaya girmiyoruz, hatta bu issue'nun aciliyeti yok ama fazla bir düzenleme gerektirmediğinden direk issue'da yazdığım gibi flex verip geçebiliriz.

**Comment by berkanyilm** [comment]
Tüm sayfalarda fixlenmiş şekilde ayarlandı.
