### ISSUE TITLE
Zafiyet Adı : Information Disclosure

### ISSUE THREAD

**Issue by hackerone-yusuf** [acikkaynak/deprem-io-frontend#49]
**Zafiyet**: **Hassas Bilgi İfşası**

**Zafiyet Açıklaması**: Kullanıcı adı , soyadı , telefon numarası gibi veriler uygulamada clear text olarak gözükmemektedir. Fakat uygulamadan dönen cevaplar incelendiğinde verilerin kullanıcıya açık bir şekilde gönderildiği gözükmektedir. Sadece arayüzde yıldızlı olarak gözükmektedir.

**Bahsi Geçen İstekler**:
![image0modified](https://user-images.githubusercontent.com/124896653/217839560-465261d5-6ef7-41a0-a7d0-3c1117bee56c.png)

![image1modified](https://user-images.githubusercontent.com/124896653/217839271-1ece4b0f-b1b4-4c4d-b10f-b14067ee417e.png)

**Verileri döndüren URL** : deprem.io/elasticsearch/msearch ve deprem.io/api/1.1/init/data?location=

**Yeniden üretme adımları**:

1.https://deprem.io/yardim-list-enkaz adresine gidin
2.Burp Suite intercepti açıp herhangi birinde "Detaya git"e basın.
![image](https://user-images.githubusercontent.com/124896653/217840141-83fbefc2-ea94-49fb-bbca-aa863c4627d4.png)
3.elasticsearch/msearch ya da /api/1.1/init/data?location= ile başlayan request gelene kadar forward edin.
![image](https://user-images.githubusercontent.com/124896653/217841041-762d3123-0eb7-42d5-a002-da4e47f22565.png)
4.Bulduğunuz zaman repeater'a yollayın.
![image](https://user-images.githubusercontent.com/124896653/217843187-ff7b5871-3ccb-49a6-8ebc-70e68f8e2ecc.png)
5.Bize gönderilen response'da veriler sansürsüz bir şekilde görülebilmekte.
![image](https://user-images.githubusercontent.com/124896653/217843785-c5c0a327-d253-4f6a-976b-64aeed4447d4.png)

**Çözüm Önerisi** : Yıldızlama işlemi sunucuda yapılıp, uygulama arayüzüne şifreli olarak gönderilmelidir.

**Comment by hmert** [comment]
@hackerone-yusuf tekrar kontrol edebilir misiniz?

**Comment by hackerone-yusuf** [comment]
> @hackerone-yusuf tekrar kontrol edebilir misiniz?

Maalesef sorun devam ediyor, request'in tamamı burada

![image](https://user-images.githubusercontent.com/124896653/217871639-498c309b-f1b1-49e6-b2f0-781f5362912e.png)

**Comment by hackerone-yusuf** [comment]
Bunun dışında şu an sitede telefon numaraları  clear text olarak görünüyor.
![image](https://user-images.githubusercontent.com/124896653/217872498-69e23c6f-3102-4e88-b343-35f5ae7827c0.png)

**Comment by izzetemredemir** [comment]
İlgileniyorum

**Comment by izzetemredemir** [comment]
Şuan bu backend buraya bağlı değil

**Comment by hackerone-yusuf** [comment]
> Şuan bu backend buraya bağlı değil

backendde hiç issue yok diye buraya açmıştım oraya mı taşıyayım
