### ISSUE TITLE
Gece ve gündüz modlarının eklenmesi

### ISSUE THREAD

**Issue by arinmis** [acikkaynak/deprem-io-frontend#63]
![image](https://user-images.githubusercontent.com/56651041/217903425-1bb819cf-69eb-4f69-8357-46bb475fef3e.png)
![image](https://user-images.githubusercontent.com/56651041/217903478-ae437091-1672-4f78-b401-617463fd1e3e.png)

**Comment by khnbzkrt** [comment]
Ben alıyorum
