### ISSUE TITLE
Yolcu Taşıma Sayfasında Filtreleme Çalışmıyor

### ISSUE THREAD

**Issue by GizemGno** [acikkaynak/deprem-io-frontend#64]
Yolcu Taşıma Sayfasında filtreleme fonksiyonu çalışmıyor, html dosyası ../assets/js/lists/ismakinesi.js script'ine point ediyor, yeni bir js dosyasında filtreleme fonksiyonunun doğru şekilde eklenmesi gerekiyor olabilir mi?

**Comment by onuruci** [comment]
Evet gerekiyor ilgileniyorum

**Comment by onuruci** [comment]
Düzelttim çalışıyor

**Comment by GizemGno** [comment]
teşekkürler eline sağlık! bir de acaba arama fonksiyonunu case insensetive yapmak mümkün olur mu? Şu an mesela yola çıkış şehri Hatay deyince çok güzel çalışıyor ama hatay deyince sonuç çıkmıyor.
