### ISSUE TITLE
Sahte Telefon numarası ve ilan girilmesi

### ISSUE THREAD

**Issue by ML-std** [acikkaynak/deprem-io-frontend#65]
sahte telefon numarası ve aynı başvurudan birden fazla olabiliyormuş. Bunun için

- numaralar +90 5XX XXX XX XX gibi kontrol edilebilir.
- İlanlar UID ile kontrol edilip, çoklanması engellenebilir 
- numaralara sms - email verification entegrasyonu yapılabilir.

**Comment by izzetemredemir** [comment]
sms verification şuan imkansız numara kontrolü ekleriz

**Comment by ML-std** [comment]
ayrıca aynı şehirden aynı şehire istek atılabiliyor. bunu afet bölgelerinden tüm türkiye gibi bir düzenleme düşünebiliriz.
![Capture](https://user-images.githubusercontent.com/56198086/217914522-15a5b8c1-bcb5-4a84-bb9d-700e06851ab8.PNG)

**Comment by ML-std** [comment]
> sms verification şuan imkansız numara kontrolü ekleriz

tahmin edebiliyorum. ancak yine eşsizlik kontrolünü bir şekilde çözmeliyiz.

**Comment by karasakalmt** [comment]
> ayrıca aynı şehirden aynı şehire istek atılabiliyor. bunu afet bölgelerinden tüm türkiye gibi bir düzenleme düşünebiliriz. İçeriğine baktığımda, şehir içi ulaşım için yazılmış. Bu ayrı bir sayfada yapılsa çok daha anlaşılır. ![Capture](https://user-images.githubusercontent.com/56198086/217914522-15a5b8c1-bcb5-4a84-bb9d-700e06851ab8.PNG)

ilceler eklenecek

**Comment by onuruci** [comment]
Numara kontrolü için js scripti yazıyorum

**Comment by karasakalmt** [comment]
@onuruci @mehmetik yapti diye biliyorum

**Comment by mehmetik** [comment]
> @onuruci @mehmetik yapti diye biliyorum

Biz sayısal değer kontrolü yaptık. Gelen veriyi JS ile sabit bir hale getirirsek oradan gelecek olan veriyi standart halinde kayıt edebiliriz. Bu noktada @onuruci veya ben frontend tarafında bir mask yapısı oluşturalım. Standart girişe zorlayalım. Gelen veriyide zorladığımız pattern'e göre kontrolünü yapmış oluruz?

**Comment by onuruci** [comment]
Telefon numarası kontrolü tam seviyede

5XX XXX XX XX
05XX XXX XX XX

user ister boşlulu ister boşluksuz şekilde girebiliyor.

Database e  "5XXXXXXXXX" şeklinde giriliyor
