### ISSUE TITLE
Konaklama Sayfası Sonrası Yönlendirme Problemi

### ISSUE THREAD

**Issue by GizemGno** [acikkaynak/deprem-io-frontend#69]
Konaklama sayfasına tıkladıktan sonra (https://deprem.io/yardim-list-konaklama) iş makinesi'ne tıklandığında gıda, yolcu taşımaya'ya tıklandığında ısınma sayfasına yönlendirme yapılıyor.

**Comment by GizemGno** [comment]
Yine js dosyası olarak konaklama.html enkaz.js'e point ediyor, belki problem oradan kaynaklanıyor olabilir.

**Comment by zafergurel** [comment]
Şu anki deprem.io sitesinde bu hata mevcut. Ancak bu repodaki kodlarda sorun yok.

Şuradaki sayfalardan da kontrol edilebilir: <https://github.com/acikkaynak/deprem-io-frontend/tree/main/yardim-saglayanlar>

Discord'da deprem.io ile ilgilenen kişiye sorun iletildi. Bu repo ile ilgili yapılacak bir şey olmadığı için kapatıyorum.
