### ISSUE TITLE
Faydali linklere linkler eklenecek

### ISSUE THREAD

**Issue by karasakalmt** [acikkaynak/deprem-io-frontend#71]
https://linktr.ee/Kurtaranev?fbclid=PAAaZOauKEGjN-ALv4-uXRukR9TCMPzmeDx8nEMUIDF6hxVGGDjLuyvPj0JGg

**Comment by zafergurel** [comment]
deprem.io'da eklenmiş başka linkler de var. Aşağıdakiler de eklenebilir. Ne dersiniz @karasakalmt?

- Afet Çözüm - Tüm Yardım Linkleri <https://afetcozum.com/?fbclid=PAAabkFMq7oD5sCj6j39SF0zgINNhEXdBpRBuwDLfE4rgQsShTHJgRhS-4Hng>
- Enkaz Dinleme Uygulaması <https://web.itu.edu.tr/sariero/dinleme.html?fbclid=PAAabbvVvqgKsFHaaPV8b1RjzuerCq1hwvEubQkyvzFjt8T71AleGIwpflHrs>
- Ev İlanları <https://misafirol.org/?fbclid=PAAabqZsyepBcJ0WaBhEn8erCckSG9Bo5alcRIQvxMH8dh_nnrA6RtuCReeMs>

**Comment by karasakalmt** [comment]
ekleyin lutfen @zafergurel
