### ISSUE TITLE
/yardim:id bağlanacak

### ISSUE THREAD

**Issue by izzetemredemir** [acikkaynak/deprem-io-frontend#75]
/yardim/:id kısmından canlı data çekilecek -> yardımKayit formu eklendi backendde dökümanı var

https://github.com/acikkaynak/deprem-io-backend

Şu endpointten test edebilirsiniz
https://deprem-27jjydhzba-ew.a.run.app/yardim/63e3940d3c12f65e945ff371

**Comment by fatihozdil** [comment]
bu detay sayfasiyle birlikte yapildi
