### ISSUE TITLE
Yardim haritalari kismini duzenleyelim

### ISSUE THREAD

**Issue by karasakalmt** [acikkaynak/deprem-io-frontend#80]
<img width="978" alt="Screen Shot 2023-02-10 at 02 43 38" src="https://user-images.githubusercontent.com/32202283/217963821-5edd0591-91d7-4c58-8cf3-e44e51765bcf.png">

**Comment by anilcanboga** [comment]
tam istek nedir?

**Comment by karasakalmt** [comment]
https://deprem.io/ da ki ile ayni yerlere gitsin haritasi su an bos olabilir bi yere gitmesine gerek yok orijinalinde de yapilmamis
