### ISSUE TITLE
Enkaz alında bulunanlar sayfasında ki "Harita Görünümüne Tıkla" linki çalışmıyor

### ISSUE THREAD

**Issue by Corepany** [acikkaynak/deprem-io-frontend#83]
## Açıklama ( Describe the bug)
Enkaz alında bulunanlar sayfasında ki "Harita Görünümüne Tıkla" linki çalışmıyor

Test yapılan link: https://dev.thechainlist.io/yardim-istekleri/enkaz.html#
Yönlendirilen hatalı link: https://dev.thechainlist.io/yardim-istekleri/enkaz-harita.html

### Adımlar (To Reproduce)
- Ana sayfa yardım listesi altında ki enkaz altında bulunanlar linkine tıkla
- Sağ üstte bulunan Harita Görünümüne tıkla

### Alınan sonuç (behavior)
Hata sayfası
<img width="817" alt="image" src="https://user-images.githubusercontent.com/9643129/217970084-5868720a-3bc8-4404-a34e-51f295b831c0.png">

### Beklenen sonuç (Expected behavior)
Haritanın görüntülenmesi

### Öncelik (Priority)
P3

### Ekran Görüntüsü (Screenshots/Video)
<img width="240" alt="image" src="https://user-images.githubusercontent.com/9643129/217969792-b20d5ebb-942f-4241-b727-737d39a9f849.png">

**Comment by yusufdeepwork** [comment]
<img width="865" alt="image" src="https://user-images.githubusercontent.com/57027351/218245772-2d8c1ec0-741d-4cd5-bbb6-2fc07892fe10.png">
@karasakalmt bu haritayı nasıl implemente edebiliriz tam anlayamadım, haritanın linkini bulamadım

**Comment by karasakalmt** [comment]
eklenmeyecek
