### ISSUE TITLE
/yardimet şehir filtresi eklenecek

### ISSUE THREAD

**Issue by izzetemredemir** [acikkaynak/deprem-io-frontend#89]
Backende /yardimet?sehir=Istanbul eklendi.

Şu backendden test edebilirsiniz
https://deprem-27jjydhzba-ew.a.run.app/yardimet?sehir=Istanbul

**Comment by izzetemredemir** [comment]
Yardım Etmek isteyen insanların bulunduğu şehiri filtreler bu endpoint

**Comment by karasakalmt** [comment]
kapanmis olmali
