### ISSUE TITLE
Özellik isteği - Gıda yardımı sağlayanların listesi

### ISSUE THREAD

**Issue by yusufdeepwork** [acikkaynak/deprem-io-frontend#9]
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/57027351/217656851-20dfc560-fae1-4842-8d34-65628df6af17.png">

Yardım Listeleri kısmında Gıda yardımı sağlayanların listesi yok, şehirlerde toplu olarak yemek dağıtımları yerleri var ama bunlar whatsapp, instagram, twitterdan geziniyor ama sağlıklı bir listeye ulaşılamıyor. Bilgi dağınıklığı mevcut. Bu issue'nun buraya ait olmadığını biliyorum ama size ulaştırmak için burdan yazıyorum. Bu özelliğin geliştirilmesi için destek vermeye hazırım

**Comment by karasakalmt** [comment]
uygundur sizi assign ediyorum diger formlardan bakarak gelistirirseniz sevinirim sorun olursa karasakalmt#1437 burdan bana ulasin

**Comment by quatronostro** [comment]
Yardım Listeleri kısmına sahipsiz kalan hayvanlar listesi veya onları sahiplenmek isteyenler için form doldurma ekranı eklenebilir
