### ISSUE TITLE
Yardım list items fix view

### ISSUE THREAD

**Issue by onuruci** [acikkaynak/deprem-io-frontend#90]
yardım listeleri itemlerinde , isim numara tarih gibi bilgiler tam düzenli durmuyor onun düzeltilmesi lazım
![Screenshot 2023-02-10 at 14-35-40 Depremzede Bildirim Formu Deprem İmece Platformu](https://user-images.githubusercontent.com/63292060/218083199-c9e4c5fc-28ee-437b-83b2-7033115c17de.png)

**Comment by yusufdeepwork** [comment]
buna başlıyorum
